/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 rural.glb --transform 
Files: rural.glb [18.26MB] > C:\Users\hp\Desktop\rs\vite-project\public\village\rural-transformed.glb [1.53MB] (92%)
Author: imwolfgang (https://sketchfab.com/imwolfgang)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/village-town-assets-adf2e5a787804ffcaaa1ad6d541278d5
Title: Village / Town Assets
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rural-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.House_Purple_Material005_0.geometry} material={materials['Material.005']} position={[-26.745, 0, -0.681]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/rural-transformed.glb')
