/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 forest.glb --transform 
Files: forest.glb [545.61KB] > C:\Users\hp\Desktop\rs\vite-project\public\forest_house\forest-transformed.glb [38.61KB] (93%)
Author: Wesai (https://sketchfab.com/Wesai)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/forest-house-5646e6a3c8834022a0e289465f0bbc5d
Title: Forest House
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/forest-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ground_main_mat_0.geometry} material={materials.main_mat} />
    </group>
  )
}

useGLTF.preload('/forest-transformed.glb')
