/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 house.glb --transform 
Files: house.glb [5.47MB] > C:\Users\hp\Desktop\rs\vite-project\public\house\house-transformed.glb [442.21KB] (92%)
Author: meesvanhout (https://sketchfab.com/meesjevanhout)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/dae-villages-greek-sculptor-house-d101c41b6dc34bd89b1006a84c507d15
Title: DAE Villages | Greek Sculptor House
*/
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useThree } from '@react-three/fiber'

export default function House(props) {
  
  const {camera}=useThree();
  console.log(camera.position)
  const { nodes, materials } = useGLTF('/house-transformed.glb')
  return (
    <group scale={2.5} dispose={null}  position={[1.7,-0.6,1]} >
      <mesh geometry={nodes.ambientLight4_HouseTEX_0.geometry} material={materials.HouseTEX} scale={0.047} />
      <mesh geometry={nodes.ambientLight4_VegetationTEX_0.geometry} material={materials.VegetationTEX} scale={0.047} />
      <mesh geometry={nodes.ambientLight4_GroundTEX_0.geometry} material={materials.GroundTEX} scale={0.047} />
    </group>
  )
}

useGLTF.preload('/house-transformed.glb')
