/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 laptop.glb --transform 
Files: laptop.glb [2.25MB] > C:\Users\hp\Desktop\rs\vite-project\public\laptop\laptop-transformed.glb [199.28KB] (91%)
Author: keskin (https://sketchfab.com/keskin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-f40e8dab87e34b1194d0a183f337961c
Title: Laptop
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Laptop(props) {
  const { nodes, materials } = useGLTF('/laptop-transformed.glb')
  return (
    <group position={[0,1,3]} scale={15}  dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.PaletteMaterial001} position={[0, 0, -0.012]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.screen} position={[0.153, 0.007, -0.082]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Metal_logo} position={[0.153, 0.007, -0.082]} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.Glass_logo} position={[0.153, 0.007, -0.082]} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.Keyboard} position={[-0.065, -0.008, 0.018]} />
    </group>
  )
}

useGLTF.preload('/laptop-transformed.glb')
