/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pink.glb --transform 
Files: pink.glb [1.7MB] > C:\Users\hp\Desktop\rs\vite-project\public\pink_house\pink-transformed.glb [121.18KB] (93%)
Author: CGulia (https://sketchfab.com/CGulia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pink-house-4c8215427b5e46818db595d6558a7172
Title: Pink House
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Pink(props) {
  const { nodes, materials } = useGLTF('/pink-transformed.glb')
  return (
    <group scale={0.7} dispose={null}  position={[-0.5,-0.4,0]}>
      <mesh geometry={nodes.Cube001_roof_0.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/pink-transformed.glb')
